### ISSUE TITLE
Add Team section to the Whitepaper

### ISSUE THREAD

**Issue by idancali** [fluidtrends/carmel#17]

**Comment by AndreiLaz** [comment]
![koreosver](https://user-images.githubusercontent.com/13683260/37774185-3d4c36ea-2de8-11e8-898c-084637ed3157.png)

KOREOS.IO

Description:
KOREOS.IO has built the most powerful EOS community in South Korea. We have a huge and tough community and spread the latest EOS news in Korean via telegrams and tweets. We know that the well developed EOS ecosystem is coming from the poweful community, and we are working to become the most influential EOS community in the world. KOREOS.IO cooperates with all BP, DAC, and all EOS ecosystem participants around the world.

**Comment by AndreiLaz** [comment]
![00b68035-7dd1-44ef-a5b7-5c946d76d01b](https://user-images.githubusercontent.com/13683260/37780755-1546ac92-2df8-11e8-96c2-340a7d860cb5.png)

**Comment by AndreiLaz** [comment]
![vincent](https://user-images.githubusercontent.com/13683260/37813326-510720f2-2e6d-11e8-8c18-4550ebd24f09.jpg)


Vincent Doare, Business Development 
Vincent is a French IT project manager in Cluj-Napoca, for 2 years, with combined studies of Business in France and Romania. He has good knowledge in team management which he acquired in the years of both work experience and while exploring his passion for football as a coach. As he collaborated many times in his work with international partners, Vincent’s objective is to be a bridge between eastern and western European countries because he deeply believes in the potential of this region. Moreover, he always wanted to improve the educational system and this is an important step to develop something that can generate that change. Enthusiasm and “joie de vivre” are the daily drivers of Vincent in his personal and professional life in Cluj-Napoca, Romania.

**Comment by AndreiLaz** [comment]
https://forums.eosgo.io/discussion/355/eos-go-logo-jpeg-and-transparent-png#latest

EOS Go is the first source for EOS. We believe in a world aligned, where collaboration is rewarded and empowered in the new blockchain internet of value. Visit https://eosgo.io to find opportunities, learn more, stay updated, and get connected. Go EOS!
