### ISSUE TITLE
Carmel Studio - some suggestions

### ISSUE THREAD

**Issue by cristofor-io** [fluidtrends/carmel#260]
- Option to allow you to revisit the completed tasks for a challenge.

- Replace the strike-through text for the completed tasks to a normal text, maybe bold, green colour
 
- Change SEE CHALLENGE DETAILS Button to be similar with CONTINUE CHALLENGE button (it's more visible and intuitive)

**Comment by adrienbenoist** [comment]
- Add a save button with a tooltip explaining the shortcut and after some challenges completed hide it. As the user should remember it ! Could show also a message after a click on save button : “you can use the shortcut! It’s faster!”
- holight color the tips files names to differentiate with normal text at lest for vw inner challenges 
- a button to restore code from the last validated task. Could be useful if the user deleted some sort of the code in a file not in purpose. Introduce also the shortcut cmd + z/Ctrl + Z
- copy last into file
- show a star when a file is modified and hide it when it is saved as many code editor or an other way
- the tags are clickable in the challenge box this could make the user lost because there is no action behind.
