### ISSUE TITLE
Task Screen

### ISSUE THREAD

**Issue by AndreiLaz** [fluidtrends/carmel#306]

**Comment by robipop22** [comment]
### Updating from the last discussion. 
If user isn't logged -> save all journey events in the browser local storage.
Warn user that he should log in order to save his progress.

If user is logged -> every time an **event** occurs, register it which will be later on blockchain.

Tips: 
```
this.props.newActivity({ type: "task", event: "started", taskId: "ddddd", challengeId: "ddddd" })
```
JSON stringify this in order to save it on the browser
