### ISSUE TITLE
Describe the community concept in the whitepaper

### ISSUE THREAD

**Issue by idancali** [fluidtrends/carmel#43]

**Comment by emil622** [comment]
Some thoughts came into my mind, I'm not sure if this issue is meant to cover them, I'll just leave them here:

Some situations might popup:
- duplicate challenges or challenges posted just for earning tokens, without providing much value
- challenges might contains mistakes, not be doable or the attached code is incorrect

I think that one way of solving these is by implementing a voting system similar to stackoverflow platform. So community could make edit suggestions, vote up or down challenges and reward users for their activity. Creators might also be useful to add a difficulty level to the challenge.

**Comment by flipace** [comment]
I really like the Stackoverflow voting system. It's really well done and could be a good fit here too.
